Fix release action

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -195,17 +195,18 @@ jobs:
 
   build-java-library:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
     needs: [build-linux-x86-64, build-linux-x86, build-linux-aarch64, build-macos-x86-64, build-macos-aarch64, build-windows-x86-64, build-windows-x86]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
       - name: Set up Java 8
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: '8'
-          server-username: MAVEN_USERNAME
-          server-password: MAVEN_PASSWORD
       - name: Download linux-x86-64
         uses: actions/download-artifact@v4
         with:
@@ -241,21 +242,33 @@ jobs:
         with:
           name: javah264-windows-x86
           path: ./src/main/resources/natives/windows-x86/
-      - name: Build and deploy
-        run: |
-          mvn -B install
-          mkdir -p release
-          cp $(find ./target -maxdepth 1 -type f -name "*.jar") ./release/
-          mvn -B deploy
+
+      - name: Grant execute permission for gradlew
+        run: chmod +x gradlew
+
+      - name: Build with Gradle
+        run: ./gradlew clean build
+
+      - name: Publish to Maven
         env:
           MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
           MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
-      - uses: actions/upload-artifact@v4
+        run: ./gradlew publish
+
+      - name: Find all JAR files
+        id: find_all_jars
+        run: |
+          JAR_PATHS=$(find build/libs -name "*.jar" | xargs)
+          if [ -z "$JAR_PATHS" ]; then
+          echo "Error: No JAR files found in build/libs."
+          exit 1
+          fi
+          echo "jar_paths=$JAR_PATHS" >> $GITHUB_OUTPUT
+
+      - name: Upload all JARs to Release Assets
+        if: success() && steps.find_all_jars.outputs.jar_paths != ''
+        uses: softprops/action-gh-release@v1
         with:
-          name: javah264-java
-          path: ./release/
-      - name: Upload release asset
-        uses: AButler/upload-release-assets@v3.0
-        with:
-          files: ./release/*
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
+          files: ${{ steps.find_all_jars.outputs.jar_paths }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
