Fix find_all_jars step

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,9 +6,6 @@ on:
       - created
   workflow_dispatch:
 
-env:
-  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
 jobs:
 
   build-linux-x86-64:
@@ -255,15 +252,15 @@ jobs:
           MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
         run: ./gradlew publish
 
-      - name: Find all JAR files
-        id: find_all_jars
+      - name: Get all JAR file paths for upload
+        id: get_jar_paths
         run: |
-          JAR_PATHS=$(find build/libs -name "*.jar" | xargs)
-          if [ -z "$JAR_PATHS" ]; then
-          echo "Error: No JAR files found in build/libs."
-          exit 1
+          JAR_FILES=$(find build/libs -name "*.jar" -print0 | xargs -0)
+          if [ -z "$JAR_FILES" ]; then
+            echo "Error: No JAR files found in build/libs."
+            exit 1
           fi
-          echo "jar_paths=$JAR_PATHS" >> $GITHUB_OUTPUT
+          echo "jar_paths=$JAR_FILES" >> $GITHUB_OUTPUT
 
       - name: Upload all JARs to Release Assets
         if: success() && steps.find_all_jars.outputs.jar_paths != ''
